# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0004_auto_20161011_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='beneficiario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficiário'),
        ),
    ]
