# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-30 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0005_processo_beneficiario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assuntoprocesso',
            options={'ordering': ('descricao',), 'verbose_name': 'Assunto de processo', 'verbose_name_plural': 'Assuntos de processos'},
        ),
        migrations.AlterModelOptions(
            name='classificacaoprocesso',
            options={'ordering': ('descricao',), 'verbose_name': 'Classificacao de processo', 'verbose_name_plural': 'Classificações de processos'},
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['nome'], 'permissions': (('print_impressoenderecamento', 'Pode imprimir impressos de endereçamento'), ('print_rel_contato_agrupado_por_processo', 'Pode imprimir relatório de contatos agrupados por processo'), ('print_rel_contato_agrupado_por_grupo', 'Pode imprimir relatório de contatos agrupados por grupo')), 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='dependenteperfil',
            options={'verbose_name': 'Dependente do perfil', 'verbose_name_plural': 'Dependentes do perfil'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AlterModelOptions(
            name='emailperfil',
            options={'verbose_name': 'Email do perfil', 'verbose_name_plural': 'Emails do perfil'},
        ),
        migrations.AlterModelOptions(
            name='enderecoperfil',
            options={'verbose_name': 'Endereço do perfil', 'verbose_name_plural': 'Endereços do perfil'},
        ),
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'ordering': ['descricao'], 'verbose_name': 'Estado civil', 'verbose_name_plural': 'Estados civis'},
        ),
        migrations.AlterModelOptions(
            name='filiacaopartidaria',
            options={'verbose_name': 'Filiação partidária', 'verbose_name_plural': 'Filiações partidárias'},
        ),
        migrations.AlterModelOptions(
            name='grupodecontatos',
            options={'ordering': ('nome',), 'verbose_name': 'Grupo de contatos', 'verbose_name_plural': 'Grupos de contatos'},
        ),
        migrations.AlterModelOptions(
            name='localtrabalho',
            options={'verbose_name': 'Local de trabalho', 'verbose_name_plural': 'Locais de trabalho'},
        ),
        migrations.AlterModelOptions(
            name='localtrabalhoperfil',
            options={'verbose_name': 'Local de trabalho do perfil', 'verbose_name_plural': 'Locais de trabalho do perfil'},
        ),
        migrations.AlterModelOptions(
            name='nivelinstrucao',
            options={'ordering': ('descricao',), 'verbose_name': 'Nível de instrução', 'verbose_name_plural': 'Níveis de instrução'},
        ),
        migrations.AlterModelOptions(
            name='operadoratelefonia',
            options={'ordering': ('descricao',), 'verbose_name': 'Operadora de telefonia', 'verbose_name_plural': 'Operadoras de telefonia'},
        ),
        migrations.AlterModelOptions(
            name='processocontato',
            options={'verbose_name': 'Processo do contato', 'verbose_name_plural': 'Processos do contato'},
        ),
        migrations.AlterModelOptions(
            name='pronometratamento',
            options={'verbose_name': 'Pronome de tratamento', 'verbose_name_plural': 'Pronomes de tratamento'},
        ),
        migrations.AlterModelOptions(
            name='statusprocesso',
            options={'ordering': ('descricao',), 'verbose_name': 'Status de processo', 'verbose_name_plural': 'Status de processos'},
        ),
        migrations.AlterModelOptions(
            name='telefoneperfil',
            options={'verbose_name': 'Telefone do perfil', 'verbose_name_plural': 'Telefones do perfil'},
        ),
        migrations.AlterModelOptions(
            name='tipoautoridade',
            options={'ordering': ('descricao',), 'verbose_name': 'Tipo de autoridade', 'verbose_name_plural': 'Tipos de autoridade'},
        ),
        migrations.AlterModelOptions(
            name='tipoemail',
            options={'ordering': ('descricao',), 'verbose_name': 'Tipo de Email', 'verbose_name_plural': 'Tipos de email'},
        ),
        migrations.AlterModelOptions(
            name='tipoendereco',
            options={'ordering': ('descricao',), 'verbose_name': 'Tipo de Endereço', 'verbose_name_plural': 'Tipos de endereço'},
        ),
        migrations.AlterModelOptions(
            name='tipolocaltrabalho',
            options={'ordering': ('descricao',), 'verbose_name': 'Tipo do local de trabalho', 'verbose_name_plural': 'Tipos de locais de trabalho'},
        ),
        migrations.AlterModelOptions(
            name='tipotelefone',
            options={'ordering': ('descricao',), 'verbose_name': 'Tipo de Telefone', 'verbose_name_plural': 'Tipos de telefone'},
        ),
        migrations.AlterModelOptions(
            name='topicoprocesso',
            options={'ordering': ('descricao',), 'verbose_name': 'Tópico de processo', 'verbose_name_plural': 'Tópicos de processos'},
        ),
        migrations.AlterField(
            model_name='assuntoprocesso',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assuntoprocesso_set', to='core.AreaTrabalho', verbose_name='Área de trabalho'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contato_set', to='cerimonial.EstadoCivil', verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nivel_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contato_set', to='cerimonial.NivelInstrucao', verbose_name='Nivel de instrução'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do pai'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Outros observações sobre o contato'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='perfil_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato_set', to=settings.AUTH_USER_MODEL, verbose_name='Perfil do usuário'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='pronome_tratamento',
            field=models.ForeignKey(blank=True, help_text='O pronome de tratamento é opcional, mas será         obrigatório caso seja selecionado um tipo de autoridade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contato_set', to='cerimonial.PronomeTratamento', verbose_name='Pronome de tratamento'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='quantos_filhos',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Quantos filhos?'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='rg_data_expedicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de expedição'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='rg_orgao_expedidor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Órgão expedidor'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo biológico'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tem_filhos',
            field=models.NullBooleanField(choices=[(None, '---------'), (True, 'Sim'), (False, 'Não')], default=None, verbose_name='Tem filhos?'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tipo_autoridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contato_set', to='cerimonial.TipoAutoridade', verbose_name='Tipo de autoridade'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=15, verbose_name='Título de eleitor'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contato_set', to='core.AreaTrabalho', verbose_name='Área de trabalho'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data nascimento'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='nivel_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependente_set', to='cerimonial.NivelInstrucao', verbose_name='Nivel de instrução'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo biológico'),
        ),
        migrations.AlterField(
            model_name='email',
            name='permissao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Permite que a Câmara envie informações         para este email?', verbose_name='Permissão:'),
        ),
        migrations.AlterField(
            model_name='email',
            name='preferencial',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Preferencial?'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(blank=True, default='', help_text='O campo endereço também é um campo de busca, nele você pode digitar qualquer informação, inclusive digitar o CEP para localizar o endereço, e vice-versa!', max_length=254, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Outros observações sobre o endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='ponto_referencia',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Pontos de referência'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='regiao_municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endereco_set', to='core.RegiaoMunicipal', verbose_name='Região municipal'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endereco_set', to='cerimonial.TipoEndereco', verbose_name='Tipo do endereço'),
        ),
        migrations.AlterField(
            model_name='filiacaopartidaria',
            name='data',
            field=models.DateField(verbose_name='Data de filiação'),
        ),
        migrations.AlterField(
            model_name='filiacaopartidaria',
            name='data_desfiliacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de desfiliação'),
        ),
        migrations.AlterField(
            model_name='grupodecontatos',
            name='contatos',
            field=models.ManyToManyField(blank=True, related_name='grupodecontatos_set', to='cerimonial.Contato', verbose_name='Contatos do grupo'),
        ),
        migrations.AlterField(
            model_name='grupodecontatos',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do grupo'),
        ),
        migrations.AlterField(
            model_name='grupodecontatos',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupodecontatos_set', to='core.AreaTrabalho', verbose_name='Área de trabalho'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='cargo',
            field=models.CharField(blank=True, default='', help_text='Ao definir um cargo e função aqui, o Cargo/Função preenchido na aba "Dados básicos", será desconsiderado ao gerar impressos!', max_length=254, verbose_name='Cargo/Função'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='endereco',
            field=models.CharField(blank=True, default='', help_text='O campo endereço também é um campo de busca. Nele você pode digitar qualquer informação, inclusive digitar o CEP para localizar o endereço, e vice-versa!', max_length=254, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='nome',
            field=models.CharField(max_length=254, verbose_name='Nome / Razão social'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='nome_social',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='regiao_municipal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='core.RegiaoMunicipal', verbose_name='Região municipal'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localtrabalho_set', to='cerimonial.TipoLocalTrabalho', verbose_name='Tipo do local de trabalho'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='contatos',
            field=models.ManyToManyField(blank=True, related_name='processo_set', to='cerimonial.Contato', verbose_name='Contatos interessados no processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data',
            field=models.DateField(verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição do processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Outras observações sobre o processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='protocolo',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Protocolo do gabinete'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='solucao',
            field=models.TextField(blank=True, default='', verbose_name='Solução do processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_set', to='cerimonial.StatusProcesso', verbose_name='Status do processo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='urgente',
            field=models.BooleanField(default=False, verbose_name='Urgente'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processo_set', to='core.AreaTrabalho', verbose_name='Área de trabalho'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='abreviatura_plural_f',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Abreviatura no feminino plural'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='abreviatura_plural_m',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Abreviatura no masculino plural'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='abreviatura_singular_f',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Abreviatura no feminino singular'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='abreviatura_singular_m',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Abreviatura no masculino singular'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='enderecamento_plural_f',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Endereçamento no feminino plural'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='enderecamento_plural_m',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Endereçamento no masculino plural'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='enderecamento_singular_f',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Endereçamento no feminino singular'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='enderecamento_singular_m',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Endereçamento no masculino singular'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='nome_por_extenso',
            field=models.CharField(default='', max_length=254, verbose_name='Nome por extenso'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='prefixo_nome_plural_f',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Prefixo no feminino plural'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='prefixo_nome_plural_m',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Prefixo no masculino plural'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='prefixo_nome_singular_f',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Prefixo no feminino singular'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='prefixo_nome_singular_m',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Prefixo no masculino singular'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='vocativo_direto_plural_f',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Vocativo direto no feminino plural'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='vocativo_direto_plural_m',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Vocativo direto no masculino plural'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='vocativo_direto_singular_f',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Vocativo direto no feminino singular'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='vocativo_direto_singular_m',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Vocativo direto no masculino singular'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='vocativo_indireto_plural_f',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Vocativo indireto no feminino plural'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='vocativo_indireto_plural_m',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Vocativo indireto no masculino plural'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='vocativo_indireto_singular_f',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Vocativo indireto no feminino singular'),
        ),
        migrations.AlterField(
            model_name='pronometratamento',
            name='vocativo_indireto_singular_m',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Vocativo indireto no masculino singular'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='operadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefone_set', to='cerimonial.OperadoraTelefonia', verbose_name='Operadora de telefonia'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='permissao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Permite que a Câmara entre em contato         com você neste telefone?', verbose_name='Permissão:'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='preferencial',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Preferencial?'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='telefone',
            field=models.CharField(max_length=100, verbose_name='Número do telefone'),
        ),
    ]
