# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-10 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0007_auto_20180910_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assuntoprocesso',
            name='created',
        ),
        migrations.RemoveField(
            model_name='assuntoprocesso',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='assuntoprocesso',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='assuntoprocesso',
            name='owner',
        ),
    ]
