# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-11 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0008_auto_20180910_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificacaoprocesso',
            options={'ordering': ('descricao',), 'verbose_name': 'Classificação de processo', 'verbose_name_plural': 'Classificações de processos'},
        ),
        migrations.AddField(
            model_name='processo',
            name='proto_orgao',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Protocolo do órgão'),
        ),
        migrations.RemoveField(
            model_name='processo',
            name='classificacoes',
        ),
        migrations.AddField(
            model_name='processo',
            name='classificacoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_set', to='cerimonial.ClassificacaoProcesso', verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_set', to='cerimonial.StatusProcesso', verbose_name='Status'),
        ),
    ]
