# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-12 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0010_auto_20180911_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filiacaopartidaria',
            old_name='data',
            new_name='data_filiacao',
        ),
        migrations.AlterField(
            model_name='contato',
            name='identidade_genero',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='identidade_genero',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Gênero'),
        ),
    ]
