# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-12 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0011_auto_20180912_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='instituicao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instituição envolvida'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='oficio_orgao',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Ofício recebido do órgão'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='orgao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Órgão demandado'),
        ),
    ]
