# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-18 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0013_auto_20180918_1138'),
    ]
