# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-18 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0015_auto_20180918_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Naturalidade'),
        ),
    ]
