# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0016_auto_20180918_1149'),
    ]
