# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0017_auto_20180918_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato_set', to='core.Municipio', verbose_name='Naturalidade'),
        ),
    ]
