# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0021_contato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='contato_set', to='core.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='naturalidade',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='Naturalidade'),
        ),
    ]
