# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 19:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0023_auto_20180921_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='localtrabalho',
            name='uf',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='distrito',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Distrito', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='regiao_municipal',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.RegiaoMunicipal', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='Município'),
        ),
    ]
