# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 19:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0024_auto_20180921_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='Município'),
        ),
    ]
