# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0025_auto_20180921_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='distrito',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_set', to='core.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', default=4891, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='regiao_municipal',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.RegiaoMunicipal', verbose_name='Região municipal'),
        ),
    ]
