# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0026_auto_20180921_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='data',
            new_name='data_abertura',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='descricao',
        ),
        migrations.AddField(
            model_name='processo',
            name='data_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Data do envio'),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Data do retorno'),
        ),
        migrations.AddField(
            model_name='processo',
            name='historico',
            field=models.TextField(blank=True, default='', verbose_name='Histórico do processo'),
        ),
    ]
