# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-24 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0029_auto_20180924_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.ForeignKey(blank=True, default=21, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato_set', to='core.Estado', verbose_name='Estado de nascimento'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='naturalidade',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='Cidade de naturalidade'),
        ),
    ]
