# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-26 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import saap.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0031_auto_20180925_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='whatsapp',
            field=models.NullBooleanField(choices=[(None, '---------'), (True, 'Sim'), (False, 'Não')], verbose_name='Possui WhatsApp?'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, validators=[saap.utils.validate_CPF], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='rg',
            field=models.CharField(blank=True, max_length=10, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=14, verbose_name='Título de eleitor'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
