# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0032_auto_20180926_1326'),
    ]

    operations = [
    ]
