# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-26 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import saap.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0035_auto_20180926_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='numero_sus',
            field=models.CharField(blank=True, default='', max_length=20, validators=[saap.utils.validate_number], verbose_name='Número do SUS'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='numero',
            field=models.IntegerField(blank=True, default=0, validators=[saap.utils.validate_number], verbose_name='Número'),
        ),
    ]
