# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-26 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0042_auto_20180926_1355'),
    ]

    operations = [
    ]
