# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0043_auto_20180926_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='preferencial',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Impressos e relatórios serão gerados sempre com os endereços preferenciais.', verbose_name='Preferencial?'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
    ]
