# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0045_auto_20180926_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='numero_sus',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número do SUS'),
        ),
    ]
