# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0048_auto_20180926_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipio', chained_model_field='municipio', default=5, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_set', to='core.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='distrito',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_set', to='core.Distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(default='', help_text='O campo endereço também é um campo de busca, nele você pode digitar qualquer informação, inclusive digitar o CEP para localizar o endereço, e vice-versa!', max_length=35, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', default=4891, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_set', to='core.Municipio', verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='regiao_municipal',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_set', to='core.RegiaoMunicipal', verbose_name='Região municipal'),
        ),
    ]
