# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-27 19:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0049_auto_20180927_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipio', chained_model_field='municipio', default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_set', to='core.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='bairro',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='municipio', chained_model_field='municipio', default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='Bairro'),
        ),
    ]
