# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-28 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0050_auto_20180927_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(default='', help_text='O campo endereço também é um campo de busca, nele você pode digitar qualquer informação, inclusive digitar o CEP para localizar o endereço, e vice-versa!', max_length=70, verbose_name='Endereço'),
        ),
    ]
