# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0051_auto_20180928_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(default='', help_text='O campo endereço também é um campo de busca, nele você pode digitar qualquer informação, inclusive digitar o CEP para localizar o endereço, e vice-versa!', max_length=35, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='endereco',
            field=models.CharField(default='', help_text='O campo endereço também é um campo de busca. Nele você pode digitar qualquer informação, inclusive digitar o CEP para localizar o endereço, e vice-versa!', max_length=35, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='estado',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='localtrabalho_set', to='core.Estado', verbose_name='Estado'),
        ),
    ]
