# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-02 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0054_auto_20181001_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Complemento'),
        ),
    ]
