# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0055_auto_20181002_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='proprio',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Próprio?'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='whatsapp',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Possui WhatsApp?'),
        ),
    ]
