# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0056_auto_20181002_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='preferencial',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='preferencial',
        ),
        migrations.RemoveField(
            model_name='localtrabalho',
            name='preferencial',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='preferencial',
        ),
        migrations.AddField(
            model_name='email',
            name='principal',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Principal'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='principal',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Principal'),
        ),
        migrations.AddField(
            model_name='localtrabalho',
            name='principal',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Principal'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='principal',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Principal?'),
        ),
    ]
