# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0057_auto_20181003_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='data_protocolo',
            field=models.DateField(blank=True, null=True, verbose_name='Data do protocolo'),
        ),
    ]
