# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-03 19:30
from __future__ import unicode_literals

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0061_auto_20181003_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='permite_contato',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text='Autorizado para contato do gabinete', verbose_name='Contato'),
        ),
    ]
