# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-10 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0064_auto_20181003_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='classificacoes',
            new_name='classificacao',
        ),
    ]
