# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0065_auto_20181010_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localtrabalho',
            old_name='nome_social',
            new_name='nome_fantasia',
        ),
        migrations.AlterField(
            model_name='processo',
            name='link_pref_orgao',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link para acompanhamento na Prefeitura ou outro Órgão'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='oficio_orgao',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Ofício recebido do Órgão'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='proto_orgao',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Protocolo do Órgão'),
        ),
    ]
