# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import saap.utils
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0067_auto_20181024_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtrabalho',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9, validators=[saap.utils.validate_CEP], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='endereco',
            field=models.CharField(blank=True, default='', help_text='O campo endereço também é um campo de busca. Nele você pode digitar qualquer informação, inclusive digitar o CEP para localizar o endereço, e vice-versa!', max_length=35, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='estado',
            field=models.ForeignKey(blank=True, default=21, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localtrabalho_set', to='core.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', default=4891, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='numero',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Número'),
        ),
    ]
