# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0068_auto_20181025_1714'),
    ]

    operations = [
    ]
