# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0070_auto_20181025_1716'),
    ]

    operations = [
    ]
