# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-29 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0071_auto_20181029_1551'),
    ]

    operations = [
    ]
