# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0073_auto_20181029_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupodecontatos',
            name='contatos',
            field=models.ManyToManyField(related_name='grupodecontatos_set', to='cerimonial.Contato', verbose_name='Contatos do grupo'),
        ),
        migrations.AlterField(
            model_name='grupodecontatos',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do grupo'),
        ),
        migrations.AlterUniqueTogether(
            name='grupodecontatos',
            unique_together=set([('nome', 'workspace')]),
        ),
    ]
