# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-10 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0074_auto_20181029_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupodecontatos',
            unique_together=set([]),
        ),
    ]
