# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0075_auto_20181210_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo biológico'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipio', chained_model_field='municipio', on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='Bairro'),
        ),
    ]
