# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-12-10 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import saap.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0076_auto_20190507_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, validators=[saap.utils.validate_CNPJ], verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='contato',
            name='ie',
            field=models.CharField(blank=True, max_length=15, verbose_name='Inscrição estadual'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(default='', max_length=35, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=35, verbose_name='Endereço'),
        ),
    ]
