# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-12-03 22:19
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0078_auto_20200915_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', default=4891, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_set', to='core.Municipio', verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', default=4891, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='Município'),
        ),
    ]
