# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-12-03 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0079_auto_20201203_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato_set', to='core.Estado', verbose_name='Estado de nascimento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_set', to='core.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', on_delete=django.db.models.deletion.CASCADE, related_name='endereco_set', to='core.Municipio', verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localtrabalho_set', to='core.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='Município'),
        ),
    ]
