# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-10 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0082_auto_20220509_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Evento',
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agenda'},
        ),
    ]
