# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-11 18:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cerimonial', '0084_auto_20220511_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='evento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 11, 18, 11, 17, 704399, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 5, 11, 18, 11, 26, 472073, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='location',
            field=models.TextField(blank=True, default='', verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='title',
            field=models.CharField(default='Evento', max_length=200, verbose_name='Título'),
        ),
    ]
