# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-11 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0086_auto_20220511_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início'),
        ),
    ]
