# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-13 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0087_auto_20220511_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='created',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='owner',
        ),
    ]
