# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-16 20:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0089_auto_20220516_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='bairro',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='localtrabalho',
            name='bairro',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='municipio', chained_model_field='municipio', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='Bairro'),
        ),
    ]
