# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-31 16:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cerimonial', '0090_auto_20220516_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 31, 16, 40, 46, 550931, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 5, 31, 16, 40, 51, 279135, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='modifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
    ]
