# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-06-01 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0091_auto_20220531_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='workspace',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.PROTECT, to='core.AreaTrabalho', verbose_name='Área de trabalho'),
            preserve_default=False,
        ),
    ]
