# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-06-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0093_auto_20220615_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupodecontatos',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AreaTrabalho', verbose_name='Área de trabalho'),
        ),
    ]
