# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-06-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0094_auto_20220615_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='link_cam',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link para acompanhamento na Câmara'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='link_pref_orgao',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Link para acompanhamento na Prefeitura ou outro Órgão'),
        ),
    ]
