# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-06-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0095_auto_20220628_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='link_facebook',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='contato',
            name='link_instagram',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='contato',
            name='link_site',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='contato',
            name='link_twitter',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Twitter'),
        ),
    ]
