# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2023-06-30 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0096_auto_20220628_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodecontatos',
            name='search',
            field=models.TextField(blank=True, default=''),
        ),
    ]
