# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2023-07-07 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerimonial', '0097_grupodecontatos_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filiacaopartidaria',
            options={'verbose_name': 'Filiação partidária do contato', 'verbose_name_plural': 'Filiações partidárias do contato'},
        ),
    ]
