version: "3.3"
services:
  saapdb:
    image: postgres:10.5-alpine
    restart: always
    container_name: postgres
    labels:
        NAME: "saapdb"
    environment:
      POSTGRES_PASSWORD: saap
      POSTGRES_USER: saap
      POSTGRES_DB: saap
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - saapdb_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - saap-net
  saap:
#   image: interlegis/saap:latest
    image: ojonathacardoso/saap:latest
#    build:
#       context: .
#       dockerfile: Dockerfile
    container_name: saap
    labels:
       NAME: "saap"
    restart: always
    environment:
       SITE_NAME: 'Sistema de Apoio à Atividade Parlamentar'
       SITE_DOMAIN: 'saap-demo.camaranh.rs.gov.br'
       DEBUG: 'False'
       DJANGO_TOOLBAR: 'False'
       EMAIL_USE_TLS: 'True'
       EMAIL_PORT: 25
       EMAIL_HOST: ''
       EMAIL_SEND_USER: ''
       EMAIL_HOST_USER: ''
       EMAIL_HOST_PASSWORD: ''
       DADOS_NOME: 'Câmara Municipal de Saapópolis'
       DADOS_ENDERECO: 'Av. XV de Novembro, 555'
       DADOS_MUNICIPIO: 'Brasília'
       DADOS_UF: 'DF'
       DADOS_CEP: '70165-900'
       DADOS_EMAIL: 'atendimento@interlegis.leg.br'
       DADOS_TELEFONE: '(61) 3303-3221'
       DADOS_SITE: 'https://www12.senado.leg.br/interlegis'
       BRASAO_PROPRIO: 'True'
       ADMIN_PASSWORD: saap_interlegis
       ADMIN_EMAIL: admin@interlegis.leg.br
    volumes:
      - saap_data:/var/interlegis/saap/data
      - saap_media:/var/interlegis/saap/media
    depends_on:
      - saapdb
    ports:
      - "80:80"
    networks:
      - saap-net
networks:
  saap-net:
    driver: bridge
volumes:
  saapdb_data:
  saap_data:
  saap_media:
