# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-10 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180831_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cep',
            options={'ordering': ('numero',), 'verbose_name': 'CEP', 'verbose_name_plural': 'CEPs'},
        ),
    ]
