# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-18 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180918_1209'),
    ]
