# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-18 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bairro_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='municipio',
            field=models.ForeignKey(default=4891, on_delete=django.db.models.deletion.CASCADE, related_name='bairros_set', to='core.Municipio', verbose_name='Município'),
        ),
    ]
