# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_municipio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estado', verbose_name='Estado'),
        ),
    ]
