# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180928_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='nome',
            field=models.CharField(max_length=254, verbose_name='Nome'),
        ),
    ]
