# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-01 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20181101_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distrito',
            unique_together=set([('nome', 'municipio')]),
        ),
        migrations.AlterUniqueTogether(
            name='regiaomunicipal',
            unique_together=set([('nome', 'municipio')]),
        ),
    ]
