# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-02-18 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201203_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operadorareatrabalho',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadorareatrabalho_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
