# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220516_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabalho',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='areatrabalho',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
    ]
