# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-05-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import image_cropping.fields
import saap.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20220517_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name'], 'permissions': (('menu_contatos', 'Mostrar menu de Contatos'), ('menu_processos', 'Mostrar menu de Processos'), ('menu_agenda', 'Mostrar menu de Agenda'), ('menu_correspondencias', 'Mostrar menu de Correspond&ecirc;ncias'), ('menu_sistema', 'Mostrar menu de Sistema')), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='avatars/', validators=[saap.core.models.avatar_validation], verbose_name='Imagem do perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de ingresso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Membro da equipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sobrenome'),
        ),
    ]
