# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-06-14 14:37
from __future__ import unicode_literals

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220614_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operadorareatrabalho',
            name='principal',
        ),
        migrations.AddField(
            model_name='operadorareatrabalho',
            name='preferencial',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, help_text="Se estiver 'Sim', após você salvar, este passa a ser a Área de Trabalho preferencial para o usuário", on=('user', 'areatrabalho'), verbose_name='Preferencial'),
        ),
    ]
