# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2023-06-30 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20220614_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabalho',
            name='operadores',
            field=models.ManyToManyField(related_name='areatrabalho_set', through='core.OperadorAreaTrabalho', to=settings.AUTH_USER_MODEL, verbose_name='Operadores'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Ativo na Casa?'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='endereco_web',
            field=models.URLField(blank=True, max_length=100, verbose_name='Página na Internet'),
        ),
    ]
