# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2023-07-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230630_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filiacao',
            options={'ordering': ('parlamentar', '-data', '-data_desfiliacao'), 'verbose_name': 'Filiação Partidária de parlamentar', 'verbose_name_plural': 'Filiações Partidárias de parlamentares'},
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Parlamentar', verbose_name='Parlamentar'),
        ),
    ]
